name: codespell
on: [push, pull_request]
jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: codespell-project/actions-codespell@master
      with:
        exclude_file: THANKS
        ignore_words_list: extint
